### ISSUE TITLE
Fix typos in animal kingdom

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#105]
Bottom of Part 2:
change ‘explorer’ to ‘explore’
“In the next section, you explorer the application code and learn which recorded elements in a DApp make it eligible for App Mining. Continue to Zero-to-DApp, 3 of 4.”

Part 3, under the heading: “Understand the Animal Kingdom Application Code”
perhaps add ‘of’ to ("the DApp instead.")
“the discussion focuses on the Blockstack Javascript library the DApp instead.” @

**Comment by lizblockstack** [comment]
Adding more typos here @moxiegirl 
blochchain:
![image](https://user-images.githubusercontent.com/39883666/51634766-13527c00-1f23-11e9-94f1-8dfa120190a8.png)
WHereas:
![image](https://user-images.githubusercontent.com/39883666/51635274-68db5880-1f24-11e9-8bb8-a93628506b57.png)
upto:
![image](https://user-images.githubusercontent.com/39883666/51635552-09317d00-1f25-11e9-8b80-17e883a4d4db.png)
