### ISSUE TITLE
How to create a test id

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#145]
Talk to @zone117x about how to create an id on the test register

**Comment by zone117x** [comment]
### To use the test registrar:
1. Go to the initial browser page where it shows the form `Create your Blockstack ID`
1. Open the developer console and execute the following
   ```js
   window.SUBDOMAIN_SUFFIX_OVERRIDE = "test-personal.id"
   ```
1. You can also use this as a js bookmarklet: 
   ```js
   javascript:(function(){window.SUBDOMAIN_SUFFIX_OVERRIDE='test-personal.id'})()`
   ```
1. Click `Create new ID`
1. The ID suffix in the text box should show `.test-personal.id` - if not then the version of the browser you are using is not using latest code (currently this feature is in the develop branch)
![image](https://user-images.githubusercontent.com/1447546/53421776-3a7dec80-39ac-11e9-8a6d-b8d80692e245.png)

---

If registration is failing, ensure the test-registrar service is currently online and working correctly. As of writing this, it is currently not working
```
$ curl https://test-registrar.blockstack.org/v1/names/test123.test-personal.id
    > {"error":"Error processing request","status":false}
```

### More info

The e2e selenium test for account creation uses this feature, see: https://github.com/blockstack/blockstack-browser/blob/37f65091ef05065ca7c2f8e2a59ab33241da3dac/test-e2e/auth/create-account.js#L18

The browser code that implements the global window flag check: https://github.com/blockstack/blockstack-browser/blob/37f65091ef05065ca7c2f8e2a59ab33241da3dac/app/js/sign-up/index.js#L101

**Comment by moxiegirl** [comment]
This is wonderful! Thank you @zone117x
