### ISSUE TITLE
Token revocation for Gaia needs to be documented

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#151]
@moxiegirl commented on [Tue Feb 26 2019](https://github.com/blockstack/blockstack-core/issues/926)

https://github.com/blockstack/gaia/issues/150
https://github.com/blockstack/gaia/pull/196

**Comment by zone117x** [comment]
@moxiegirl See API usage for `POST ${hubUrl}/revoke-all/${address}` here https://github.com/blockstack/gaia/blob/develop/README.md#http-api

We are still working on adding revocation support to blockstack.js https://github.com/blockstack/blockstack.js/issues/607
