### ISSUE TITLE
Add the Awario App reviewer

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#164]
* Updating existing App Mining Docs that say there are three reviewers
* Add documentation around Awario process

**Comment by friedger** [comment]
Also add reference to Awario Data sheet as mentioned in https://github.com/blockstack/app-mining/issues/30#issuecomment-484967067

**Comment by moxiegirl** [comment]
The awario documentation went out a few weeks ago. @friedger I'll create a new issue for your topic.

https://docs.blockstack.org/develop/app-reviewers.html#awario
