### ISSUE TITLE
typo in browser FAQ

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/docs.blockstack#168]
<img width="696" alt="Screenshot 2019-03-13 at 10 03 32" src="https://user-images.githubusercontent.com/25477905/54266337-781b7180-4577-11e9-9202-735cc85840a3.png">
https://docs.blockstack.org/browser/faq_general.html

Simply put, in a decentralized internet, _you your data_, not the applications or services you use.

**Comment by moxiegirl** [comment]
@jasperjansz Thanks, I'll get that fixed.
