### ISSUE TITLE
Add illustrative graphics to the reviewers document

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#176]
https://blog.blockstack.org/introducing-new-internet-labs-the-digital-rights-reviewer-for-app-mining/

**Comment by friedger** [comment]
also include graphics from https://github.com/blockstack/app-mining/blob/master/DigitalRightsAuthScoringCriteria.pdf

**Comment by moxiegirl** [comment]
@GinaAbrams New Internet Labs is equivalent to Digital Rights reviewer correct? Do you think the illustrations proposed by @friedger should be added?

**Comment by friedger** [comment]
Or an equivalent

**Comment by moxiegirl** [comment]
@friedger I would not publish those --- I'd just use them to construct final ones.

**Comment by GinaAbrams** [comment]
hey @moxiegirl I think an equivalent could be helpful to the community. 🙏
