### ISSUE TITLE
Update the Gaia limits in the docs and the FAQ

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#193]
Gina ii:44AM
Is there any limit to storage on Gaia at the moment? e.g for following example:

more than lk daily active user which generate more than 3-5k posts and 40k replies can blockstack and gaia handle this content?

@aaron aaron ii:45AM
nope, the only limit is on a single user not being able to do more than 100 writes a minute
4 replies Last reply today at 8:35 AM

moxiegirl 12 minutes ago
Did we remove the 25MB file upload limit?

aaron 12 minutes ago
no -- that's still there

moxiegirl 11 minutes ago
cool, thanks. I'll add the 100 writes one to the FAQ and the docs

aaron 11 minutes ago
so, the rate at which someone can upload is like 2500 MB per minute

**Comment by hstove** [comment]
It would also be useful to know exactly how the rate limited works - I.e is it on a rolling average basis? If you wait 60 seconds, is the rate limit clear for you?

**Comment by moxiegirl** [comment]
@kantai Can you expand on the rate limiting behavior as per Hank above?

**Comment by kantai** [comment]
if you violate the rate limit, you have to wait a minute before submitting another request.
