### ISSUE TITLE
App Mining FAQ: Update link to algorithm in the timeline section 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/docs.blockstack#196]
In the section linked here under  App Mining Timeline on [FAQ](https://app.co/mining#what-is-the-app-mining-timeline) `Blockstack team performs App Mining algorithm as referenced here [link].` the link is broken. Can we update to [this blog post](https://blog.app.co/how-app-minings-ranking-algorithm-works/)?

**Comment by moxiegirl** [comment]
this if fixed by #197
