### ISSUE TITLE
Guidelines for Blockstack sign in buttons

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/docs.blockstack#199]
One thing related to establishing our brand is making sure it's instantly recognizable. 

Currently, every Blockstack app has their own way of designing their sign in buttons, and their own copy. See examples:

<img width="391" alt="Screenshot 2019-04-05 at 10 09 49" src="https://user-images.githubusercontent.com/25477905/55613594-63ec1e00-578b-11e9-87df-c1bbca215c26.png">
<img width="262" alt="Screenshot 2019-04-05 at 10 10 19" src="https://user-images.githubusercontent.com/25477905/55613596-65b5e180-578b-11e9-9525-8fd0bb67d4a4.png">
<img width="288" alt="Screenshot 2019-04-05 at 10 13 35" src="https://user-images.githubusercontent.com/25477905/55613632-7cf4cf00-578b-11e9-9b04-08a0b4fa42c0.png">

**My proposal:**
Create guidelines for implementing a _Sign in with Blockstack_ button, much like [the Google Sign-in guidelines](https://developers.google.com/identity/branding-guidelines).

Includes:

- Copy for the button (sign in, vs. log in, etc.)
- Design with the new brand guidelines that works in all circumstances
- Guidelines for how to use it, and for how not to use it
- Source files
- A place in the docs somewhere

**Comment by moxiegirl** [comment]
@jasperjansz This is a wonderful idea.  I think we can add a whole section UI/UX guidelines eventually. This is a similar type of project I worked on at Atlassian:

https://docs.atlassian.com/aui/5.2/index.html
