### ISSUE TITLE
https requirement for applications

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#201]
@friedger commented on [Wed Mar 20 2019](https://github.com/blockstack/app-mining/issues/68)

The lioapp get score 4,4 but is hosted on http domain, not https

---

@jeffdomke commented on [Fri Mar 29 2019](https://github.com/blockstack/app-mining/issues/68#issuecomment-478029242)

hey @larrysalibra can you please address this. 

---

@larrysalibra commented on [Mon Apr 01 2019](https://github.com/blockstack/app-mining/issues/68#issuecomment-478540741)

Using https seems like it should be a basic criteria for app mining eligibility.  We can create a policy to catch these and flag these during our review, but it seems like something that can be caught before app mining reviews even starts either by looking at the list or making the application form not accept URLs that don't start with https://. Thoughts @hstove @GinaAbrams @pstan26 ? 

---

@jeffdomke commented on [Fri Apr 05 2019](https://github.com/blockstack/app-mining/issues/68#issuecomment-480306311)

Sounds like the next step is to update our docs with an `https` requirement.

**Comment by moxiegirl** [comment]
@GinaAbrams let me know where you want this like in general requirements equivalent to auth or someplace else.

**Comment by GinaAbrams** [comment]
@moxiegirl sorry for the delay here yes, lets please add this to the general requirements equivalent to auth. 🙏 thank you!

**Comment by GinaAbrams** [comment]
hey @moxiegirl is this in progress or enforced via the submission form? 🙏

**Comment by moxiegirl** [comment]
@GinaAbrams This issue was to update the FAQ. I think I forgot to specify https.

**Comment by moxiegirl** [comment]
@GinaAbrams Please review this new language regarding https: https://deploy-preview-230--docsproduction.netlify.com/faqs/allfaqs#what-qualifies-my-app-to-compete-in-app-mining

**Comment by GinaAbrams** [comment]
Looks great to me! Thanks Mary 🙏
