### ISSUE TITLE
App Mining Eligibility FAQ 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/docs.blockstack#218]
Hey @moxiegirl can we add a point to "What qualifies my app to compete in App Mining?" 

`The app must be hosted at a dedicated URL (e.g. not something like netlify). ` 🙏 thank you!

**Comment by moxiegirl** [comment]
Convo for changes: 

moxiegirl [1:10 PM]
@Gina This statement “The app must be hosted at a dedicated URL (e.g. not something like netlify). ” can you clarify what you mean.  Our documentation is hosted on Netlify --- that’s what Netlify does. Do you mean it must have a registered domain and the application URL should use it?

moxiegirl [1:11 PM]
`The app must be have its own registered domain and be hosted at a URL associated with that domain`

Gina [1:11 PM]
replied to a thread:
Yeah, sorry for the confusion. That is what I meant. Thank you! 

moxiegirl [1:12 PM]
Salright. Thanks for the assist.
