### ISSUE TITLE
npm install Issue for "Hello, Blockstack" Tutorial

### ISSUE THREAD

**Issue by skarabocu** [blockstack/docs.blockstack#234]
I started to the "Hello, Blockstack" tutorial and came to the point that I needed to install the dependencies. However, I received the following error,
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/sinankarabocuoglu/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:304:12)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1000:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:405:11)
gyp ERR! stack     at Socket.emit (events.js:196:13)
gyp ERR! stack     at Pipe.<anonymous> (net.js:586:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sinankarabocuoglu/Desktop/Computer Projects/Blockstack/hello-world-tutorial/node_modules/tiny-secp256k1
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sinankarabocuoglu/.npm/_logs/2019-04-30T18_38_24_052Z-debug.log

I searched for an answer at https://forum.blockstack.org/ but could not find one. I also tried to uninstall and reinstall Node.js and npm for several times and still could not fix the problem. Any help would be appreciated.

**Comment by moxiegirl** [comment]
@skarabocu Can you tell me about your environment?  OS and version. Did you check the npm log file -- or perhaps you can attach it here.

**Comment by skarabocu** [comment]
@moxiegirl I am using Mac iOS Mojave 10.14. 
Yes, I checked the npm log file, yet I could not find the source of the error. I am attaching the entire log file to here though, so you can check it as well. Thanks for the help!
[2019-05-01T16_11_06_307Z-debug.log](https://github.com/blockstack/docs.blockstack/files/3135139/2019-05-01T16_11_06_307Z-debug.log)

**Comment by moxiegirl** [comment]
@skarabocu This is likely related to your environment. Did you google this error you are getting `npm ERR! tiny-secp256k1@1.1.0 install: node-gyp rebuild` and follow the suggestions?

**Comment by skarabocu** [comment]
@moxiegirl I found out npm does not support Python 3, so I changed the configuration to Python 2.7. However, now I am getting this error:

> tiny-secp256k1@1.1.0 install /Users/sinankarabocuoglu/Desktop/Computer Projects/Blockstack/hello-world-tutorial/node_modules/tiny-secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/native/addon.o
../native/addon.cpp:240:2: warning: ignoring return value of function declared
      with 'warn_unused_result' attribute [-Wunused-result]
        secp256k1_ec_privkey_negate(context, tweak_negated); // returns 1 always
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:320:21: error: no matching member function for call to
      'BooleanValue'
                strict = info[3]->BooleanValue();
                         ~~~~~~~~~^~~~~~~~~~~~
/Users/sinankarabocuoglu/.node-gyp/12.1.0/include/node/v8.h:2559:8: note: 
      candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/sinankarabocuoglu/.node-gyp/12.1.0/include/node/v8.h:2562:51: note: 
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../native/addon.cpp:82:23: error: no matching member function for call to
      'BooleanValue'
                return info[index]->BooleanValue() ? SECP256K1_EC_COMPRE...
                       ~~~~~~~~~~~~~^~~~~~~~~~~~
../native/addon.cpp:142:21: note: in instantiation of function template
      specialization '(anonymous namespace)::assumeCompression<2,
      Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested
      here
        const auto flags = assumeCompression<2>(info, pA);
                           ^
/Users/sinankarabocuoglu/.node-gyp/12.1.0/include/node/v8.h:2559:8: note: 
      candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/sinankarabocuoglu/.node-gyp/12.1.0/include/node/v8.h:2562:51: note: 
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../native/addon.cpp:80:21: warning: comparison of integers of different signs:
      'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return __isPointCompressed(p...
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:82:23: error: no matching member function for call to
      'BooleanValue'
                return info[index]->BooleanValue() ? SECP256K1_EC_COMPRE...
                       ~~~~~~~~~~~~~^~~~~~~~~~~~
../native/addon.cpp:174:21: note: in instantiation of function template
      specialization '(anonymous namespace)::assumeCompression<1,
      Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested
      here
        const auto flags = assumeCompression<1>(info, p);
                           ^
/Users/sinankarabocuoglu/.node-gyp/12.1.0/include/node/v8.h:2559:8: note: 
      candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/sinankarabocuoglu/.node-gyp/12.1.0/include/node/v8.h:2562:51: note: 
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../native/addon.cpp:80:21: warning: comparison of integers of different signs:
      'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return __isPointCompressed(p...
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:89:23: error: no matching member function for call to
      'BooleanValue'
                return info[index]->BooleanValue() ? SECP256K1_EC_COMPRE...
                       ~~~~~~~~~~~~~^~~~~~~~~~~~
../native/addon.cpp:189:21: note: in instantiation of function template
      specialization '(anonymous namespace)::assumeCompression<1,
      Nan::FunctionCallbackInfo<v8::Value> >' requested here
        const auto flags = assumeCompression<1>(info);
                           ^
/Users/sinankarabocuoglu/.node-gyp/12.1.0/include/node/v8.h:2559:8: note: 
      candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/sinankarabocuoglu/.node-gyp/12.1.0/include/node/v8.h:2562:51: note: 
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../native/addon.cpp:87:21: warning: comparison of integers of different signs:
      'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
4 warnings and 4 errors generated.
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sinankarabocuoglu/Desktop/Computer Projects/Blockstack/hello-world-tutorial/node_modules/tiny-secp256k1
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sinankarabocuoglu/.npm/_logs/2019-05-01T16_52_24_489Z-debug.log

**Comment by moxiegirl** [comment]
@skarabocu Looks like there is a new problem in the `node-gyp` package. 

https://github.com/nodejs/node-gyp/issues/1734

I just ran the `npm install`and `npm start` on my Mac which has this env:

```
$ node -v
v11.1.0
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
$  npm --version
6.9.0
``

**Comment by skarabocu** [comment]
@moxiegirl I solved the problem after playing around with the python and npm versions, and file access settings. Thank you so much!

**Comment by moxiegirl** [comment]
@skarabocu Great! Glad you sorted it.
