### ISSUE TITLE
Document authentication flow with centralized servers

### ISSUE THREAD

**Issue by friedger** [blockstack/docs.blockstack#259]
There are a few articles that describe ways to authenticate a user with a server like the blockstack forum, a chat server, ..

* https://forum.blockstack.org/t/authenticating-a-user-to-a-3rd-party-server/7016
* https://forum.blockstack.org/t/adding-blockstack-authentication-to-a-centralized-app/6252
* https://github.com/blockstack/blockstack-ruby
* https://github.com/blockstack/omniauth-blockstack

The documentation should help to solve issues like https://github.com/opencollective/opencollective/issues/1749 or https://github.com/tootsuite/mastodon/issues/10344

**Comment by moxiegirl** [comment]
@friedger You mean like this?

https://docs.blockstack.org/develop/auth_provider.html

**Comment by friedger** [comment]
@moxiegirl  You are ahead of all the things! That tutorial is great.

I was also looking for a high level description so that developers can integrate blockstack into their current web site that does not use ruby and omniauth. I am just going through that with OpenCollective, they use one-time email password authentication (and nextjs). Not sure what exactly would be useful:
* guide for product owner
* how to add blockstack when using username/password
* how to add blockstack when using one-time passwords via email/SMS
* how to add blockstack when using webauthn

**Comment by moxiegirl** [comment]
@friedger Glad you like it! 

"guide for a product owner" --- would that be like how to brand?

The other three, from a technical angle, do we have apps that illustrate these?

**Comment by CodeSlip** [comment]
This guide is great for Rails clients/backends, is there any chance we can get an update for Node & JS environments?

**Comment by moxiegirl** [comment]
@CodeSlip we can add that to the list.  Right now, unfortunately, this ticket isn't in the roadmap.  @friedger if you see examples of projects that do these things, please let me know.
