### ISSUE TITLE
How to authenticate or log into Blockstack from a Chrome Extension

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#272]
@markmhx commented on this issue here: https://github.com/blockstack/blockstack.js/issues/518

@zone117x "It can't be done within a standalone chrome extension. however, you could get blockstack auth working on a normal webapp, then integrate a web extension's behavior with that webapp"

Question: By integrating web extension's behaviour with webapp, do you mean by using iframe in the extension to load the webapp? Is there another approach better  than using iframe?

@zone117x An iframe within the extension probably isn't the best approach.
zenhub https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?hl=en-US
and pushbullet https://chrome.google.com/webstore/detail/pushbullet/chlffgpmiacpedhhbkiomidkjlcfhogd?hl=en
look like good examples of an extension delegating auth flow to a webapp
chrome.google.com
ZenHub for GitHub
ZenHub – Project Management Inside GitHub
chrome.google.com
Pushbullet
Bringing together your devices, friends, and the things you care about.

**Comment by markmhx** [comment]
@zone117x could you provide @moxiegirl here with the exact sort of guidance you'd put in documentation regarding authentication within browser extensions?

**Comment by moxiegirl** [comment]
@markmhx @zone117x What we actually need is some example code.  I checked the references Matt required for the corresponding source I could look at.  These two examples seem to be closed source.  So, the problem isn't actually an explanation --- conceptually it is possible, but the example code is what they really need.

**Comment by markmhx** [comment]
@zone117x Want to provide some sample code here that @moxiegirl could use for documentation?

**Comment by zone117x** [comment]
This would be more like a demo project rather than just sample code. 
I gave some more guidance here: https://github.com/blockstack/blockstack.js/issues/518

**Comment by markmhx** [comment]
@moxiegirl is this guidance sufficient enough to draft up some initial docs?

**Comment by moxiegirl** [comment]
@markmhx I'll take a look at this.  Should be enough. I'll look at this after Clarity goes out.
