### ISSUE TITLE
Update ToDo Tutorial docs

### ISSUE THREAD

**Issue by babaskate** [blockstack/docs.blockstack#278]
update the todo tutorial docs in regards to the referenced version of node. I couldn't get the yarn install to work otherwise. 

https://github.com/blockstack/blockstack.org/commit/9b243745cd899d87aecb56d799364904befc9cdf#diff-4a1252ef0bffb7e1f6d46c2c737e449dR10

**Comment by moxiegirl** [comment]
@babaskate It looks like this got lost in our repos. I'm sorry that it got lost. I'll take a look at your concern this week and see if was addressed or if it still needs addressing.

**Comment by babaskate** [comment]
Thanks. It was very minor and it’s possible you’ve already updated the
tutorials.

**Comment by moxiegirl** [comment]
This should be fixed. Please open a new issue if you are still seeing this.
