### ISSUE TITLE
Add a blue button w/ a CTA at the end of Zero to Dapp

### ISSUE THREAD

**Issue by xanbots** [blockstack/docs.blockstack#292]
Blue button right before the "Congratulations" section on [this page](https://docs.blockstack.org/develop/zero_to_dapp_4.html) that says "See the Winning Teams ->"  and links to app.co/mining/latest

**Comment by cuevasm** [comment]
Winning is strange, what about 'Meet Last Month's Top Earners' or something along those lines. Win - reward, etc. is what we're trying to stay away from. It's a payout that they earn, not a reward they win.

**Comment by cuevasm** [comment]
or just Top Earners
