### ISSUE TITLE
Test the cli-blockstack install docs and update

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#320]
* Confirm that the blockstack.js is a req.
* Dependency in package.json or update install docs and readme as needed.

**Comment by moxiegirl** [comment]
Documentation worked as documented in our installation guide.  User was attempting a local build on Linux.  Add information for building from source.

**Comment by john-light** [comment]
It might be worth adding a "dependencies" section that documents the need for `build-essentials`, `git` if downloading via `git clone`, and the necessary node.js version (if a specific node version is needed; I was having issues trying to install with the most recent node version but not the Latest LTS version).
