### ISSUE TITLE
Zero to dapp tutorial references signature fund

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/docs.blockstack#329]
From https://docs.blockstack.org/develop/zero_to_dapp_1.html: "You’ll also learn about the Blockstack Signature Fund and the Application Mining program which awards funds to DApp developer every month"

We should remove references to the Signature fund?

**Comment by moxiegirl** [comment]
@diwakergupta  We have several mentions of the signature fund throughout the docs can you provide more context for your ask so I can determine more about which mentions to remove and why?

https://docs.blockstack.org/org/overview.html
https://docs.blockstack.org/org/wallet-intro.html
https://docs.blockstack.org/org/wallet-intro.html

**Comment by diwakergupta** [comment]
My understanding is that it's not a thing anymore, so yes we should ideally remove references from everywhere. @jeffdomke does that sound right?
