### ISSUE TITLE
Add new FAQ to stackstoken.com (Angellist login)

### ISSUE THREAD

**Issue by blocks8** [blockstack/docs.blockstack#330]
New FAQ to add to stackstoken.com: 

**I tried to login to CoinList with my AngelList account and now I can’t sign in. How do I access my account?**  

If you previously set up your CoinList account by logging in with your AngelList credentials and you are having issues signing into your account, you must create a separate password for Coinlist. You can do this by going to https://stackstoken.net/login and selecting “Forgot your Password?”.

Next, please enter the email associated with your AngelList account and select “Send recovery email.” This will then allow you to create a unique password for your CoinList account. 

Going forward, you can access your CoinList account by logging in with your email and new password.

**Comment by moxiegirl** [comment]
Fixed by #331
