### ISSUE TITLE
Simplify Hello Blockstack tutorial

### ISSUE THREAD

**Issue by TerjeNorderhaug** [blockstack/docs.blockstack#334]
The [Hello, Blockstack](https://docs.blockstack.org/browser/hello-blockstack.html) javascript tutorial requires installation of Yeoman:

````shell
npm install -g yo
yo blockstack
````

However, this extra installation step can be eliminated by directing npm to use yo during the blockstack app creation, simplifying the process:

````shell
npm create yo blockstack
````

**Comment by moxiegirl** [comment]
@TerjeNorderhaug Thanks for the suggestion. I'm working on incorporating this.
