### ISSUE TITLE
Update App Mining Docs: Awario 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/docs.blockstack#399]
Can we please update this section: https://docs.blockstack.org/develop/app-reviewers.html#awario 

Awario: 

Awario provides data about app awareness through measure of reach, mentions, and growth. Awario rankings start counting at the start of the month the app was submitted, and the results are incorporated into the rankings the month following. This means that any data used in calculations is from the previous month. New apps to the program do not incorporate this score on their first month of being enrolled.

As of October 2019, Awario ranks apps based on Blended Awareness. 

Blended Awareness is comprised of 3 parts: 
    1. A binary scoring on social networks. i.e. you get a number out of 5 max (1 point for any Mention registered on Facebook, Twitter, YouTube, Reddit, or Instagram). 
    2. A “Reach score” for any Mentions in the News/Blog section. The Reach will have log10 scoring applied to it. 
    3. A growth score, this will be calculated the same way, just limited to the growth in Reach from the News/Blog Mentions. Each of these three pieces will make up 1/3 of your overall Awario score. 

Awario provides the following information for ranking:

- Reach is the estimated online Reach of the Mention collected on the brand. For example, reach would include how many impressions a tweet mentioning the app actually generated.
- The log of the reach score is calculated by = if(X2=0, "", log10(X2))
- The Awario growth score is the percentage change in total reach from the last month to this month (NOT log10)
- Awario Average is calculated by reach/growth Z. If growth is omitted, then this is just reach z.

------ 
Tagging @cuevasm to please review and suggest any edits prior to asking @moxiegirl to implement. 🙏

**Comment by cuevasm** [comment]
Awario provides data about app awareness by scanning the web for 'Mentions' of the app name. The Awario score for App Mining is a result of measuring the Reach of these Mentions (specifically, Blog/News mentions), combined with the growth rate of overall Reach, combine with a binary examination of Mentions on social media. 

Awario rankings start counting at the start of the month the app was submitted, and the results are incorporated into the rankings the month following. This means that any data used in calculations is from the previous month. New apps to the program do not incorporate this score on their first month of being enrolled.

As of October 2019, Awario ranks apps based on Blended Awareness.

Blended Awareness is comprised of 3 parts:
1. A binary scoring on social networks. i.e. you get a number out of 5 max (1 point for any Mention registered on Facebook, Twitter, YouTube, Reddit, or Instagram).
2. A “Reach score” for any Mentions in the News/Blog section. The Reach will have log10 scoring applied to it.
3. A growth score, this will be calculated the same way, just limited to the growth in Reach from the News/Blog Mentions. 

Each of these three pieces will make up 1/3 of your overall Awario score. (@hstove may want to add more color here?)

Awario provides the following information for ranking:
- Reach is the estimated online Reach of the Mention collected on the brand. For example, reach would include how many impressions a tweet mentioning the app actually generated.
- The log of the reach score is calculated by = if(X2=0, "", log10(X2))
- The Awario growth score is the percentage change in total reach from the last month to this month (NOT log10)
- Awario Average is calculated by reach/growth Z. If growth is omitted, then this is just reach z.

**Comment by hstove** [comment]
Yes, I'm happy about all of this. Some notes:

- You don't get a growth score for the first month that you have Awario data. So, your score is only comprised of reach and social.
- You don't get a growth score if your reach last month was less than 1000. This is designed to prevent huge growth percentage outliers.
- When we transition from the old Awario system to the new one, no one will get a growth score for the first month.
