### ISSUE TITLE
Reskin the documentation

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#433]
Any new design should visually reflect our existing properties. In an implementation, it should anticipate translation as well.

- [ ] Identify a design resource (either a person or theme)
- [ ] Prototype the new design with the existing content and a few translation examples
       This should also help to reveal any changes required to the project and/or page configuration. We also need to check for issues in source code trees.
- [ ] Stage the new design with existing content.
- [ ] Document the new design for authoring

**Comment by johndmulhausen** [comment]
We'll work on this outside of this issue
