### ISSUE TITLE
Clarify App Mining Scoring

### ISSUE THREAD

**Issue by njordhov** [blockstack/docs.blockstack#463]
The [app rankings](https://github.com/blockstack/docs.blockstack/blob/master/_develop/app-rankings.md) explanation page is mangled, with sentences appearing in wrong sections, confusing the workings of the app ranking algorithm.

PR #462 reorganizes the document to clarify the app ranking algorithm.

**Comment by moxiegirl** [comment]
@njordhov That language is adding content --- I've asked the original author to review your PR.

**Comment by johndmulhausen** [comment]
Page has been removed; closing issue
