### ISSUE TITLE
Update Awario docs

### ISSUE THREAD

**Issue by cuevasm** [blockstack/docs.blockstack#475]
Update bullet 2 to:
- Medium and Meetup.com links will not count in your Reach score for the time being. The way Reach is calculated for these sites is notably inaccurate. Awario is shipping updates to this soon, so Blockstack can revisit then. Medium.com and Meetup.com Reach will be zeroed out for everyone.

Fix typo in last bullet '**your** Awario Dashboard'

Thanks!

**Comment by moxiegirl** [comment]
This was done.
