### ISSUE TITLE
Unclarity in Clarity Reference

### ISSUE THREAD

**Issue by njordhov** [blockstack/docs.blockstack#480]
Several entries in the [Clarity reference ](https://docs.blockstack.org/core/smart/clarityref) includes a sentence construct like:

    The .... function attempts to ‘unpack’ the ... argument

See the entries for [default-to](https://docs.blockstack.org/core/smart/clarityref#default-to), [expects](https://docs.blockstack.org/core/smart/clarityref#expects) and [expects-err!](https://docs.blockstack.org/core/smart/clarityref#expects-err). For example:

> The default-to function attempts to ‘unpack’ the second argument: if the argument is a (some ...) option, it returns the inner value of the option. If the second argument is a (none) value, default-to it returns the value of default-value.`

It is not clear what 'unpack’ means. The quotes suggest it's an introduced concept. Here are some suggested starting points for a revision:

> The default-to function returns the contained value of the second argument, or the value of the first argument if the second argument is `none`.

or

> If the second argument is an [optional type](https://docs.blockstack.org/core/smart/clarityref#some) returns the contained value of the second argument; If the second argument  is [none](https://docs.blockstack.org/core/smart/clarityref#none) returns the value of the first argument.

**Comment by moxiegirl** [comment]
@njordhov Thanks for issue. I'll look into clarifying this with the dev team.

**Comment by moxiegirl** [comment]
Issue moved to [blockstack/blockstack-core #1205](https://github.com/blockstack/blockstack-core/issues/1205) via [**ZenHub**](https://www.zenhub.com/)
