### ISSUE TITLE
Clarity tutorial failures

### ISSUE THREAD

**Issue by njordhov** [blockstack/docs.blockstack#483]
Several steps in the tutorial fail when executed in the current CLI:

    # clarity-cli execute /data/db $DEMO_ADDRESS.tokens mint! $DEMO_ADDRESS 100000
    Transaction execution error: 
    Unchecked(TypeValueError(UIntType, Int(100000)))

and

    # echo "(get owner (map-get name-map (tuple (name 10))))" | clarity-cli eval $DEMO_ADDRESS.names /data/db
    Program execution error: 
    Unchecked(UndefinedFunction("map-get"))

Submitted PR #482 

Also, the link to clarity-cli at the end of the tutorial is incorrect.

Correction in PR #484

**Comment by moxiegirl** [comment]
@njordhov Thanks for the issue. I'll check with the dev team to see how the image changed.

**Comment by johndmulhausen** [comment]
Closing due to old PRs that address
