### ISSUE TITLE
Dangling balance in Clarity tutorial

### ISSUE THREAD

**Issue by njordhov** [blockstack/docs.blockstack#486]
In the [simple Clarity example](https://docs.blockstack.org/core/smart/tutorial.html#task-2-review-a-simple-clarity-program) the `mint!` function binds a `balance` but never uses it:

```lisp
(define-public (mint! (amount int))
   (let ((balance (get-balance tx-sender)))
     (token-credit! tx-sender amount)))
```

Meanwhile, `token-credit!` returns a response type but it is not unwrapped by `mint!`. I suppose this is left to the caller?

**Comment by johndmulhausen** [comment]
I believe this was removed; no such function shows up there any longer
