### ISSUE TITLE
Add page about Blockstack design and branding

### ISSUE THREAD

**Issue by friedger** [blockstack/docs.blockstack#528]
The page could contain 
* links to https://github.com/blockstack/designs/tree/master/design-system 
* links to https://branding.blockstack.design/

**Comment by johndmulhausen** [comment]
This should be something that lives on www rather than the docs

**Comment by friedger** [comment]
There is some design documentation for Connect button.

John Mulhausen <notifications@github.com> schrieb am Sa., 6. Juni 2020,
02:40:
