### ISSUE TITLE
Search is broken (CORS issues)

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs.blockstack#534]
Search requests seem to fail due to CORS issues. 

<img width="1427" alt="Screen Shot 2020-03-16 at 9 19 55 AM" src="https://user-images.githubusercontent.com/1671228/76779165-239d6a00-6768-11ea-89cc-4358ef9f17be.png">

**Comment by diwakergupta** [comment]
The CORS errors are likely a red-herring. I think our Site Search 360 config is busted:

<img width="929" alt="Screenshot 2020-03-16 12 59 28" src="https://user-images.githubusercontent.com/15990/76782030-0bd4de80-6786-11ea-94c2-41497e316bc7.png">

cc/ @jeffdomke

**Comment by johndmulhausen** [comment]
I believe this has fixed itself since being opened. Closing as no repro for the time being.
