### ISSUE TITLE
Update Clarity Docs title

### ISSUE THREAD

**Issue by cuevasm** [blockstack/docs.blockstack#545]
'Hello World' is a bit vague and it's not clear if that was intentional or not. Also in meta preview it doesn't offer a whole lot to indicate that you're headed to the right place. 

Would suggest something like: "Clarity Tutorial: Hello World" or even "Get Started With Clarity Smart Contracts" given we need to train people to associate the name Clarity with smart contracts as much as possible in the early days. 

https://docs.blockstack.org/core/smart/tutorial.html

**Comment by agraebe** [comment]
There are 3 things here that I'd like to separate for the discussion:

1) Information architecture (navigation title)
I'd resist prefixing every tutorial with "Clarity", seems very duplicated and not thought out (in the navigation at least). There's already a "Getting Started" section (the landing of the smart contract docs) with a doc page: "Introduction to Clarity". I'd caution on hammering in the name wherever we can. The docs should be laser-focused on the goals of the users. The name should be communicated very clearly throughout the user discovery process on the testnet and website. Docs should support subtle but not be used as a vehicle for that IMHO.

2) Docs page title (your main point I believe @cuevasm )
Currently, the navigation title is used as the docs page title. I think that's broken. `Hello World` should be prefixed with the sections of the document, something like `Blockstack Smart Contracts (Clarity) > Tutorials > Hello World"

3) Meta tags
As for the meta preview, I'm all for more descriptive language there. It looks like this part hasn't been maintained much (looking at other docs pages). The current description is set to:
`Blockstack Clarity: Hello World Tutorial`. This is broken as well. With a fix in the doc's title, all that information would be provided. I'd rather use the meta to describe what the TL;DR of the page is.

**Comment by cuevasm** [comment]
Didn't mean hammering everywhere, but some association between the name of
the language and what you can do with it (goals of users) is needed. Right
now it's pretty unclear on all counts - I had to double check I was even in
the right place after clicking. Aaron suggested adding the prefix but I
agree we wouldn't want to overuse.

This was me trying to suggest a quick update that would help in the interim
given there's a lot to be decided about docs and we're going to have these
particular docs in front of people a lot in the coming days with testnet.

Very agnostic in terms of how you decide to solve!

**Comment by agraebe** [comment]
Got that, thanks for flagging. I created a PR that changes the title of the page and the header to prefix "Clarity". I believe this can be a short-term solution.
