### ISSUE TITLE
Update "Android DApps" tutorial with Blockstack Connect

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs.blockstack#558]
https://docs.blockstack.org/android/tutorial.html

Update according to the changes made to the underlying app generator and remove reliance on local authenticator installation.

**Comment by markmhx** [comment]
@friedger I spoke with @yknl about seeing if you could help us with this documentation update and any related code needed to get Android support fully functional with Blockstack Connect. Is this something you could do over the next couple of weeks? And if so, want to take a look at the current documentation linked here and let me know if you have any questions about how to go about this?

**Comment by friedger** [comment]
This issue is not dependent on the generator. Hosting a manifest.json should be enough.

I will work on an update of the SDK and the documentation.

**Comment by markmhx** [comment]
Thanks! Much appreciated 🙏

**Comment by markmhx** [comment]
@friedger Checking in to see how this is going?
