### ISSUE TITLE
Update "iOS DApps" tutorial with Blockstack Connect

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs.blockstack#559]
https://docs.blockstack.org/ios/tutorial.html

Update according to the changes made to the underlying app generator.

**Comment by markmhx** [comment]
@yknl Any updates on this work?

**Comment by yknl** [comment]
PR's for this were merged a few weeks ago:
https://github.com/blockstack/blockstack-ios/pull/92
Doc: https://github.com/blockstack/docs.blockstack/pull/594
