### ISSUE TITLE
Add richer introduction with screenshots to Connect overview

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs.blockstack#560]
https://docs.blockstack.org/develop/connect/overview.html

Explain and preview the design advantages for developers and users alike.

**Comment by markmhx** [comment]
@jasperjansz will provide two animated gif screenshares: one for user registration and one for sign in then I'll use them to create two section on the introduction page that highlight their respective features

**Comment by jasperjansz** [comment]
@markmhx sign up/in vids [https://app.zenhub.com/files/145732562/d954c6f3-8f92-4373-bf3e-977e30630c7c/download](https://app.zenhub.com/files/145732562/d954c6f3-8f92-4373-bf3e-977e30630c7c/download)

**Comment by markmhx** [comment]
@jasperjansz is going to get the videos here onto the CDN and embed, so no worries about that now @aulneau.
