### ISSUE TITLE
Add required Ubuntu dependencies for testnet

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/docs.blockstack#575]
I was able to run the testnet on [Ubuntu Server 20.04 LTS](https://ubuntu.com/download/server) using Virtualbox and 1gb of RAM, but there were a few things I had to install first.

I ran into the same dependency issues on Linux Mint XFCE 19, and this should apply to any Ubuntu-based installation. This information should be added to the [Run a Stacks Testnet Node](https://docs.blockstack.org/core/smart/neon-node.html) page.

Before installing Rust, the following packages should be installed:

- build-essential
- cmake
- libssl-dev
- pkg-config

`sudo apt-get install build-essential cmake libssl-dev pkg-config`

After that the instructions work as expected :slightly_smiling_face:

**Comment by agraebe** [comment]
thanks for surfacing, added a callout in the docs!
