### ISSUE TITLE
Connect: Todo List tutorial linking to an outdated project

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs.blockstack#601]
The [Todo List](https://docs.blockstack.org/browser/todo-list.html) tutorial requires cloning the [Blockstack Todos](https://github.com/blockstack/blockstack-todos) project, which was not updated for 6+ months.

Later in the tutorial, it is assumed that the sources are from the updated [app generator](https://github.com/blockstack/blockstack-app-generator) project, which doesn't have the Todo screens/features.

cc @hstove

**Comment by markmhx** [comment]
I'm not too clear on what exact work is requested by this issue. @agraebe can you clarify?

**Comment by agraebe** [comment]
The todo project should be updated and used in the tutorial

**Comment by markmhx** [comment]
Any particular deadline for this change or is it an ASAP kind of thing but not terrible urgent?

**Comment by agraebe** [comment]
Should be aligned with the Connect release. Right now, devs can't go through the tutorial and succeed. Not urgent (given postponed Connect release) but important is my feeling.

**Comment by hstove** [comment]
I have a PR in the Todos project that updates it. Must have forgotten to tag or add reviewers.

https://github.com/blockstack/blockstack-todos/pull/37

**Comment by markmhx** [comment]
That PR has since been merged. @hstove should we close this issue out now?

**Comment by agraebe** [comment]
Could someone do an end to end review of the full tutorial? To make sure it works as intended?

**Comment by markmhx** [comment]
@hstove have you had a chance to do that already or want me to?

**Comment by hstove** [comment]
Yes, I definitely went through it, but I'm also the one who made the changes. Someone else should QA, I think.

**Comment by timstackblock** [comment]
The app is not pointing to connect and I can login without issue and create a new account. See screen shots below.

![Screen Shot 2020-06-15 at 10.32.27 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/56ca6d6d-152f-4957-936b-6b19c4d1e6f9)
![Screen Shot 2020-06-15 at 10.30.30 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/3ca17751-a136-474a-b604-4824426bfc9b)

But the documentation still needs updating with new images and notes to reflect the removal of the blockstack brower and the switch to connect.

![Screen Shot 2020-06-15 at 10.33.52 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/549d0a99-95b7-492a-a580-0d01e61d0d8b)

**Comment by markmhx** [comment]
Let's hold off QA'ing this for now. I'm currently re-doing the whole thing.

**Comment by markmhx** [comment]
Actually, let's close this out and track the changes separately with https://github.com/blockstack/blockstack-todos/issues/40.

Thanks for this initial review @timstackblock  🙏

**Comment by timstackblock** [comment]
@markmhx The hello-world app is not currently working with connect running the instructions in the readme here https://github.com/blockstack/blockstack-app-generator gives the results below.

<img width="1434" alt="Screen Shot 2020-06-15 at 10 43 39 AM" src="https://user-images.githubusercontent.com/49165468/84671379-4cfb9c80-aef5-11ea-9201-b44e2a671fb7.png">

**Comment by markmhx** [comment]
@timstackblock the generator app is now fixed but also removed from this tutorial so no longer relevant per se here. cc @hstove
