### ISSUE TITLE
Add guidance for checking for transaction status in app

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs.blockstack#608]
For Blockstack Connect docs

**Comment by agraebe** [comment]
This is covered in the docs backlog for mainnet cc @johndmulhausen

**Comment by markmhx** [comment]
Are we tracking that in another issue and if so, mind linking here?

**Comment by markmhx** [comment]
☝🏻 ping

**Comment by agraebe** [comment]
From my understanding, this is captured in here: https://github.com/blockstack/docs.blockstack/issues/636.

@markmhx are you maybe proposing to use Connect directly to check the tx status?

**Comment by markmhx** [comment]
For this particular issue, I'm thinking we just need some sort of guidance in the docs (presumably in ["Signing transactions"](https://docs.blockstack.org/develop/connect/use-with-clarity.html)) for developers to call an API with the transaction ID and get its status. #636 looks relevant to me so I'll add a comment there specifying this particular need.

I do believe additionally that we'll probably want to add transaction status support directly into Connect at some point. But we can tackle that in a different issue.

**Comment by agraebe** [comment]
Let me add that quickly
