### ISSUE TITLE
Add redirect for Zero-to-Dapp pages

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs.blockstack#645]
As reported in https://github.com/blockstack/blockstack.org/issues/1123, we could use redirects for all the previous Zero-to-Dapp paths so that any remaining inbound links don't dead-end visitors.

Perhaps we should have them all go to https://docs.blockstack.org/browser/todo-list.html for now since that's our main tutorial at the moment?

**Comment by johndmulhausen** [comment]
This is done! 👍
