### ISSUE TITLE
Windows version of Zero to DApp

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#66]
Need to write a windows-specific version of Zero to DApp

**Comment by moxiegirl** [comment]
https://github.com/blockstack/docs.blockstack/pull/106

**Comment by TeunVanSambeek** [comment]
Any progress here?
I also just installed node-v10.16.0-x64 but >npm install doesn't work
(is not recognized as internal command)
How do I continue on my windows 10 machine?

**Comment by TeunVanSambeek** [comment]
Sorry, I see now the Windows track callout: Zero-to-Dapp instructions for Windows now available. As you work through the tutorial pages which have a “Windows” version appear with a track callout.

Will try it now!
