### ISSUE TITLE
Fix relevant menu expansion upon page load

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs.blockstack#668]
Whenever I load the todo list tutorial, the "Data Indexing" menu appears expanded instead of the "Authentication" one where it resides.

<img width="1280" alt="Screen Shot 2020-07-21 at 13 07 22" src="https://user-images.githubusercontent.com/28991/88064528-b19cbd80-cb6b-11ea-8259-d29315553c54.png">

**Comment by agraebe** [comment]
I believe the system stores what menus the user opened/collapsed in a state session/cookie. So, when you refresh it opens the menu items that you had opened before.

What we would need is a function that will automatically open/collapse the navigation based on the loaded page.

@aulneau [new docs system](https://blockstack-docs.vercel.app/browser/todo-list) seem to have the needed functionality, so I'm going to close this ticket. Please re-open if I misunderstood @markmhx
