### ISSUE TITLE
Show active menu item

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/docs.blockstack#677]
![image](https://user-images.githubusercontent.com/25477905/89180804-ca0ccf00-d592-11ea-9625-1f94da00e4ce.png)

We should indicate the currently active menu item by making it blue

**Comment by aulneau** [comment]
resolved with https://github.com/blockstack/docs.blockstack/commit/66b1a5a9cdea9827394baeaf2ce13130ddf3aa58
