### ISSUE TITLE
Typo: calling an address a publisher key

### ISSUE THREAD

**Issue by jcnelson** [blockstack/docs.blockstack#699]
`For example, if the same publisher key, SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR...`  <-- Should be "address" or "public key hash".  Also, `SZ` isn't a valid address prefix -- neither in mainnet nor testnet (we only support `SP`, `ST`, `SM`, and `SN`).

https://blockstack-docs-git-feat-next.blockstack.vercel.app/smart-contracts/principals

**Comment by aulneau** [comment]
fixed with #707
