### ISSUE TITLE
Numbered content seems misaligned

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs.blockstack#709]
Content on [this page](https://blockstack-docs-git-feat-next.blockstack.vercel.app/smart-contracts/counter-tutorial#step-2-running-tests) shows numbers at the end of a long sentence whereas the numbers should show up at the top.

<img width="712" alt="Screen Shot 2020-08-10 at 4 13 23 PM" src="https://user-images.githubusercontent.com/1671228/89840251-a0205300-db24-11ea-862e-b21f62899f0b.png">

**Comment by aulneau** [comment]
fixed with #707
