### ISSUE TITLE
Expand authentication tutorial to include storage provider selection

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#72]
makeAuthRequest now includes a new parameter for indicating whether not the onboarding flow is going to include storage provider flow.  

https://github.com/blockstack/blockstack.js/pull/569

This information will be covered in the blog going out with the release.

Need to expand the tutorial for Authentication to provide guidance around this new workflow.  

cc: @hstove @markmhx

**Comment by markmhx** [comment]
Here's the forum post with relevant information for reference: https://forum.blockstack.org/t/user-choice-of-gaia-hub-now-available-during-onboarding/7026

That post is the only method we used to announce this new functionality and should remain accurate until further changes to the functionality are possibly made.

@moxiegirl I recommend we sync up about terminology before tackling this documentation.
