### ISSUE TITLE
Expose GAIA repo docs in the documentation site

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/docs.blockstack#82]
Currently, we are pointing users to the GAIA repo documentation. We want to expose that documentation to customers and to search.

**Comment by markmhx** [comment]
This work includes providing instructions for setting up Gaia hubs with:

- Docker compose (Virginia's work)
- Digital Ocean (Hank's work)

**Comment by moxiegirl** [comment]
Ok, this is its own issue and so is #80 @markmhx --- they are two blocks of work.
