### ISSUE TITLE
Show section navigation on mobile

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs.blockstack#87]
It seems as though we simply hide the section navigation on mobile, which makes it hard or impossible for mobile visitors to find certain sections unless they're linked from inside the content.

Can we add this navigation to mobile as well?

<img width="1421" alt="screen shot 2019-01-04 at 15 29 21" src="https://user-images.githubusercontent.com/28991/50692928-c707d080-1035-11e9-8f46-8c4095351038.png">

<img width="520" alt="screen shot 2019-01-04 at 15 29 28" src="https://user-images.githubusercontent.com/28991/50692935-ca9b5780-1035-11e9-948c-f9b4df60441c.png">

<img width="452" alt="screen shot 2019-01-04 at 15 29 33" src="https://user-images.githubusercontent.com/28991/50692934-ca02c100-1035-11e9-9569-83ae9a61845e.png">

**Comment by moxiegirl** [comment]
@markmhx There should be a way to show it on mobile, yes.
