### ISSUE TITLE
Clarify terminology in Browser storage provider documentation

### ISSUE THREAD

**Issue by markmhx** [blockstack/docs.blockstack#88]
Per comments on [the draft in Paper](https://paper.dropbox.com/doc/How-you-control-your-data--AUP9wtdg2PCSp~f9Gc8JIegeAg-I8hBik1W38DsSK4vlrlRI), I'd like to clarify the terminology we use in the [Browser storage provider documentation](https://docs.blockstack.org/browser/storage-provider.html) aka "How you control your data" to ensure we're using terms like "storage provider" and "Gaia hub" in ways that are consistent with guidance provided on GitHub for [Gaia](https://github.com/blockstack/gaia) and [Gaia hubs](https://github.com/blockstack/gaia/tree/master/hub) in particular.

**Comment by moxiegirl** [comment]
@markmhx We had a meeting about this and you took on the action item of coming back with some terms. Any updates now that we are getting to release Gaia docs?

**Comment by markmhx** [comment]
@moxiegirl Sorry I've been behind on getting you this list of terminology. I'll review shortly and get you this – and assigning this issue to myself as such.

**Comment by moxiegirl** [comment]
@markmhx I'm going to mark this as done. Reopen if you disagree.
